### ISSUE TITLE
Build Additional Scrapper

### ISSUE THREAD

**Issue by bird25** [user512/teacher_dashboard#19]
What to get: 

- [x] track last update date #18 

- [x] track submission date #18

- [x] challenge description #17

**Comment by user512** [comment]
Scraper now returns completed_at and updated_at:
https://github.com/user512/fcc-profile-scraper/commit/71dfae61264848c14c0a6fba4faa3e5ac6781a8b

Demo: https://fcc-profile-scraper.herokuapp.com/user/user512

**Comment by user512** [comment]
Scraper now returns challenge title and instructions
https://github.com/user512/fcc-profile-scraper/commit/b68f2a7f4c3d83ce930f9fda13314d5ef6d7f100

Demo: https://fcc-profile-scraper.herokuapp.com/challenge/Say Hello to HTML Elements?

**Comment by user512** [comment]
@bird25 Scraper is now completed, if you have a moment, you are welcome to test any edge cases that I have not covered.

Simply append challenge name to this url https://fcc-profile-scraper.herokuapp.com/challenge/ for testing.
